"""empty message

Revision ID: 2264d14fe4c4
Revises: 73c62386f842
Create Date: 2026-02-08 02:13:54.010863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2264d14fe4c4'
down_revision = '73c62386f842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_characters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.create_table('favorite_locations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'location_id')
    )
    op.drop_table('favorites_characters')
    op.drop_table('favorites_locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_locations',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='favorites_locations_location_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_locations_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'location_id', name='favorites_locations_pkey')
    )
    op.create_table('favorites_characters',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorites_characters_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_characters_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'character_id', name='favorites_characters_pkey')
    )
    op.drop_table('favorite_locations')
    op.drop_table('favorite_characters')
    # ### end Alembic commands ###
